<definitions name="HelloService"
targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <message name="getBMIRequest">
        <part name="page" type="xsd:int"/>
    </message>
    <message name="getBMIResponse">
        <part name="bmi" />
    </message>
    <portType name="Hello_PortType">
        <operation name="getNews">
            <input message="tns:getBMIRequest"/>
            <output message="tns:getBMIResponse"/>
        </operation>
    </portType>
    <binding name="Hello_Binding" type="tns:Hello_PortType">
        <soap:binding style="rpc"
transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="getNews">
            <soap:operation soapAction="getNews"/>
            <input>
                <soap:body
encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
namespace="urn:examples:helloservice"
use="encoded"/>
            </input>
            <output>
                <soap:body
encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
namespace="urn:examples:helloservice"
use="encoded"/>
            </output>
        </operation>
    </binding>
    <service name="BMI_Service">
        <documentation>WSDL File for HelloService</documentation>
        <port binding="tns:Hello_Binding" name="BMI_Port">
            <soap:address
location="http://localhost:3030/soap/" />
        </port>
    </service>
</definitions>